export const ARTICLES_LOADING = 'ARTICLES_LOADING';
export const ARTICLES_FAILED = 'ARTICLES_FAILED';
export const ADD_ARTICLES = 'ADD_ARTICLES';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_AUTH = 'GET_AUT';
